In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[1:4]

array([12, 13, 14])

In [5]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [6]:
arr[4]

np.int64(15)

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [8]:
arr[5,4]

np.int64(30)

In [10]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [12]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [13]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [14]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_i]