In [1]:
import numpy as np

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
arr2 = a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [8]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [9]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [10]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [11]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
a1 // a2

array([0, 0, 0, 0, 0])

In [13]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [14]:
l = [10,20,30,40]
arr = np.array(l)

In [15]:
for i in l:
    print(i + 10)

20
30
40
50


In [16]:
arr + 10

array([20, 30, 40, 50])

In [17]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [20]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[4:6] *10

array([50, 60])

In [25]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
a
b = a

In [29]:
b[0] = 99

In [30]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [33]:
A

array([[1, 2],
       [3, 4]])

In [34]:
B

array([[5, 6],
       [7, 8]])

In [35]:
A @ B

array([[19, 22],
       [43, 50]])

In [36]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [37]:
A

array([[1, 2],
       [3, 4]])

In [38]:
A.T

array([[1, 3],
       [2, 4]])

In [39]:
B

array([[5, 6],
       [7, 8]])

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [41]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [45]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [47]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [48]:
a = np.vsplit(c,4)


In [49]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
